spring.application.name=back-end

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=${MONGODB_URI}

management.endpoint.health.show-details=always
management.health.db.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.web.resources.static-locations=classpath:/static/

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8